language: c
sudo: required
dist: trusty # modern Python

before_install:
  - sudo apt-get update
  - sudo apt-get install --yes g++ cmake make libqt4-dev libboost-dev
  - sudo pip install cpp-coveralls

install:
  - mkdir build-dir
  - cd build-dir
  - cmake ..
  - make

before_script:
  - sudo apt-get install --yes valgrind

script:
  - valgrind ./src/test/bacteria_test

after_success:
  - coveralls --include src
